/**
 * This software is being provided per FARS 52.227-14 Rights in Data - General.
 * Any redistribution or request for copyright requires written consent by the
 * Department of Veterans Affairs.
 */
package iti.xds_b._2007;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-03-01T19:41:39.187-07:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "urn:ihe:iti:xds-b:2007", name = "XDSRegistry")
@XmlSeeAlso({oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class, oasis.names.tc.ebxml_regrep.xsd.query._3.ObjectFactory.class, gov.samhsa.schema.ds4p.xdsbregistry.message.ObjectFactory.class, org.hl7.v3.ObjectFactory.class, oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface XDSRegistry {

    @WebResult(name = "PatientRegistryRecordRevisedResult", targetNamespace = "", partName = "PatientRegistryRecordRevisedResult")
    @Action(input = "urn:hl7-org:v3:PRPA_IN201302UV02", output = "urn:hl7-org:v3:MCCI_IN000002UV01")
    @WebMethod(operationName = "PatientRegistryRecordRevised", action = "urn:hl7-org:v3:PRPA_IN201302UV02")
    public java.lang.Object patientRegistryRecordRevised(
        @WebParam(partName = "input", name = "RegistryRequest", targetNamespace = "http://schema.samhsa.gov/ds4p/XDSbRegistry/Message")
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest input
    );

    @WebResult(name = "UpdateDocumentSetResult", targetNamespace = "", partName = "UpdateDocumentSetResult")
    @Action(input = "urn:ihe:iti:2010:UpdateDocumentSet", output = "urn:ihe:iti:2010:UpdateDocumentSetResponse")
    @WebMethod(operationName = "UpdateDocumentSet", action = "urn:ihe:iti:2010:UpdateDocumentSet")
    public java.lang.Object updateDocumentSet(
        @WebParam(partName = "input", name = "RegistryRequest", targetNamespace = "http://schema.samhsa.gov/ds4p/XDSbRegistry/Message")
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest input
    );

    @WebResult(name = "AdhocQueryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", partName = "RegistryStoredQueryResult")
    @Action(input = "urn:ihe:iti:2007:RegistryStoredQuery", output = "urn:ihe:iti:2007:RegistryStoredQueryResponse")
    @WebMethod(operationName = "RegistryStoredQuery", action = "urn:ihe:iti:2007:RegistryStoredQuery")
    public oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse registryStoredQuery(
        @WebParam(partName = "input", name = "AdhocQueryRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0")
        oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryRequest input
    );

    @WebResult(name = "DeleteDocumentSetResult", targetNamespace = "", partName = "DeleteDocumentSetResult")
    @Action(input = "urn:ihe:iti:2010:DeleteDocumentSet", output = "urn:ihe:iti:2010:DeleteDocumentSetResponse")
    @WebMethod(operationName = "DeleteDocumentSet", action = "urn:ihe:iti:2010:DeleteDocumentSet")
    public java.lang.Object deleteDocumentSet(
        @WebParam(partName = "input", name = "RegistryRequest", targetNamespace = "http://schema.samhsa.gov/ds4p/XDSbRegistry/Message")
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest input
    );

    @WebResult(name = "PatientRegistryRecordAddedResult", targetNamespace = "", partName = "PatientRegistryRecordAddedResult")
    @Action(input = "urn:hl7-org:v3:PRPA_IN201301UV02", output = "urn:hl7-org:v3:MCCI_IN000002UV01")
    @WebMethod(operationName = "PatientRegistryRecordAdded", action = "urn:hl7-org:v3:PRPA_IN201301UV02")
    public java.lang.Object patientRegistryRecordAdded(
        @WebParam(partName = "input", name = "PRPA_IN201302UV", targetNamespace = "urn:hl7-org:v3")
        hl7.v3.PRPAIN201302UV input
    );

    @WebResult(name = "PatientRegistryDuplicatesResolvedResult", targetNamespace = "", partName = "PatientRegistryDuplicatesResolvedResult")
    @Action(input = "urn:hl7-org:v3:PRPA_IN201304UV02", output = "urn:hl7-org:v3:MCCI_IN000002UV01")
    @WebMethod(operationName = "PatientRegistryDuplicatesResolved", action = "urn:hl7-org:v3:PRPA_IN201304UV02")
    public java.lang.Object patientRegistryDuplicatesResolved(
        @WebParam(partName = "input", name = "RegistryRequest", targetNamespace = "http://schema.samhsa.gov/ds4p/XDSbRegistry/Message")
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest input
    );

    @WebResult(name = "RegisterDocumentSetResult", targetNamespace = "", partName = "RegisterDocumentSetResult")
    @Action(input = "urn:ihe:iti:2007:RegisterDocumentSet-b", output = "urn:ihe:iti:2007:RegisterDocumentSet-bResponse")
    @WebMethod(operationName = "RegisterDocumentSet", action = "urn:ihe:iti:2007:RegisterDocumentSet-b")
    public java.lang.Object registerDocumentSet(
        @WebParam(partName = "input", name = "RegistryRequest", targetNamespace = "http://schema.samhsa.gov/ds4p/XDSbRegistry/Message")
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest input
    );
}
