
package iti.xds_b._2007;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import samhsa.ds4p.xdsbregistry.DocumentRegistryService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-03-01T19:41:38.973-07:00
 * Generated source version: 2.6.0
 * 
 */
public final class XDSRegistry_XDSRegistryHTTPEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://samhsa.gov/ds4p/XDSbRegistry/", "DocumentRegistryService");

    private XDSRegistry_XDSRegistryHTTPEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DocumentRegistryService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DocumentRegistryService ss = new DocumentRegistryService(wsdlURL, SERVICE_NAME);
        XDSRegistry port = ss.getXDSRegistryHTTPEndpoint();  
        
        {
        System.out.println("Invoking patientRegistryRecordRevised...");
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest _patientRegistryRecordRevised_input = null;
        java.lang.Object _patientRegistryRecordRevised__return = port.patientRegistryRecordRevised(_patientRegistryRecordRevised_input);
        System.out.println("patientRegistryRecordRevised.result=" + _patientRegistryRecordRevised__return);


        }
        {
        System.out.println("Invoking updateDocumentSet...");
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest _updateDocumentSet_input = null;
        java.lang.Object _updateDocumentSet__return = port.updateDocumentSet(_updateDocumentSet_input);
        System.out.println("updateDocumentSet.result=" + _updateDocumentSet__return);


        }
        {
        System.out.println("Invoking registryStoredQuery...");
        oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryRequest _registryStoredQuery_input = null;
        oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse _registryStoredQuery__return = port.registryStoredQuery(_registryStoredQuery_input);
        System.out.println("registryStoredQuery.result=" + _registryStoredQuery__return);


        }
        {
        System.out.println("Invoking deleteDocumentSet...");
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest _deleteDocumentSet_input = null;
        java.lang.Object _deleteDocumentSet__return = port.deleteDocumentSet(_deleteDocumentSet_input);
        System.out.println("deleteDocumentSet.result=" + _deleteDocumentSet__return);


        }
        {
        System.out.println("Invoking patientRegistryRecordAdded...");
        hl7.v3.PRPAIN201302UV _patientRegistryRecordAdded_input = null;
        java.lang.Object _patientRegistryRecordAdded__return = port.patientRegistryRecordAdded(_patientRegistryRecordAdded_input);
        System.out.println("patientRegistryRecordAdded.result=" + _patientRegistryRecordAdded__return);


        }
        {
        System.out.println("Invoking patientRegistryDuplicatesResolved...");
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest _patientRegistryDuplicatesResolved_input = null;
        java.lang.Object _patientRegistryDuplicatesResolved__return = port.patientRegistryDuplicatesResolved(_patientRegistryDuplicatesResolved_input);
        System.out.println("patientRegistryDuplicatesResolved.result=" + _patientRegistryDuplicatesResolved__return);


        }
        {
        System.out.println("Invoking registerDocumentSet...");
        gov.samhsa.schema.ds4p.xdsbregistry.message.RegistryRequest _registerDocumentSet_input = null;
        java.lang.Object _registerDocumentSet__return = port.registerDocumentSet(_registerDocumentSet_input);
        System.out.println("registerDocumentSet.result=" + _registerDocumentSet__return);


        }

        System.exit(0);
    }

}
